name = "Alacritty"
version = "v1.0.0"

documentation = """
Custom Alacritty configuration.
"""

[enabled]
macos = true
manjaro = true

[variables]
ENV = [
  "TERM=screen-256color",
]

[variables__macos]
CASKS = [
  "alacritty",
]

[variables__manjaro]
PACMAN = [
  "alacritty",
]

[[link]]
name = "Config file"
path_to_target = "./config/alacritty.yml"
path_to_symlink = "$HOME/.config/alacritty/alacritty.yml"
