name = "Python"
version = "v1.0.0"
enabled = true

documentation = """
Local python configuration.
"""

[variables]
FORMULAE = [
  "pipx",
  "pyenv",
]
ENV = [
  "VIRTUALFISH_HOME='$HOME/.virtualenvs'",
  "PIPX_DEFAULT_PYTHON='$HOME/.pyenv/shims/python'",
]
POST_CONFIG = [
  "pyenv init - | source",
]

[[hooks]]
name = "INSTALL"
path_to_script = "./bin/hook__install__macos.sh"
priority = 1
