name = "Python"
version = "v1.0.0"

documentation = """
Local python configuration.
"""

[enabled]
macos = true
manjaro = true

[variables]
ENV = [
  "VIRTUALFISH_HOME='$HOME/.virtualenvs'",
  "PIPX_DEFAULT_PYTHON='$HOME/.pyenv/shims/python'",
]
POST_CONFIG = [
  "pyenv init - | source",
]

[variables__macos]
FORMULAE = [
  "pipx",
  "pyenv",
]

[variables__manjaro]
PACMAN = [
  "python",
  "pyenv",
]

[[shell_script_hook]]
name = "INSTALL"
path_to_script = "./bin/hook__install__macos.sh"
priority = 1
