name = "NodeJS"
version = "v1.0.0"

documentation = """
NodeJS local configuration.
"""

[enabled]
macos = false
manjaro = false

[variables]
PACMAN = [
  "npm",
]

# [[links]]
# name = "Initialization file"
# path_to_target = "./config/init.el"
# path_to_symlink = "$HOME/.config/emacs/init.el"
# 
# [[links]]
# name = "Custom org based configuration"
# path_to_target = "./config/conf.org"
# path_to_symlink = "$HOME/.config/emacs/conf.org"
