name = "Neovim"
version = "v1.0.0"

documentation = """
Advanced neovim configuration.

After deploying the links you need to execute the <<BOLD>>:PlugInstall<<RESET>> command to install the plugins.
"""

[enabled]
macos = true
manjaro = true

[variables]
ENV = [
  "EDITOR=nvim",
]

[variables__macos]
FORMULAE = [
  "neovim",
  "fzy", "fzf",  # Fuzzy finder tools.
  "ripgrep",  # Fast alternative to grep, optinal dependency for Telescope
  "fd", # Fast alternative to find, optional dependency for Telescope
  "wget", # Required by Mason
]
ALIAS = [
  "vim=nvim",
]

[variables__manjaro]
PACMAN = [
  "neovim",  # Base package.
  "fzy",
  "ripgrep",
  "fzf",
  "wget",
]
ALIAS = [
  "vim=nvim",
]

[[link]]
name = "Configuration directory"
path_to_target = "./config"
path_to_symlink = "$HOME/.config/nvim"

# [[hook]]
# name = "INSTALL"
# path_to_script = "./bin/hook__install.sh"
# priority = 0
