name = "Ranger"
version = "v1.0.0"

documentation = """
Configuration for the ranger file browser.
"""

[enabled]
macos = true
manjaro = true

[variables]
ALIAS = [
  "r=ranger",
]

[variables__macos]
FORMULAE = [
  "ranger",
]

[variables__manjaro]
PACMAN = [
  "ranger",
  "python-pillow",  # For the kitty based image previews.
]

[[link]]
name = "Configuration directory"
path_to_target = "./config"
path_to_symlink = "$HOME/.config/ranger"

