name = "Ranger"
version = "v1.0.0"
enabled = true

documentation = """
Configuration for the ranger file browser.
"""

[variables]
PACMAN = [
  "ranger",  # Base package.
  "python-pillow",  # For the kitty based image previews.
]
ALIAS = [
  "r=ranger",
]

[[links]]
name = "Configuration directory"
path_to_target = "./config"
path_to_symlink = "$HOME/.config/ranger"

