name = "Keybase"
version = "v1.0.0"

documentation = """
Basic keybase configuration.
"""

[enabled]
macos = true
manjaro = true

[variables__macos]
CASKS = [
  "keybase",
]

[variables__manjaro]
PACMAN = [
  "keybase",  # Base package.
  "kbfs", "keybase-gui",  # Additional required packages..
]

[[link__macos]]
name = "Keybase CLI"
path_to_target = "/Applications/Keybase.app/Contents/SharedSupport/bin/keybase"
path_to_symlink = "$HOME/.local/bin/keybase"

[[link__macos]]
name = "Keybase git remote extension"
path_to_target = "/Applications/Keybase.app/Contents/SharedSupport/bin/git-remote-keybase"
path_to_symlink = "$HOME/.local/bin/git-remote-keybase"
