name = "Homebrew"
version = "v1.0.0"

documentation = """
Homebrew package manager configuration that will collect and install the required
packages.

Before you can use the dotmodules based package mangement, you need to prepare <<BOLD>>homebrew<<RESET>> itself with the following steps:

1. Install <<BOLD>>homebrew<<RESET>> with the usual method.
2. On a fresh system you need to make sure the necessary <<BOLD>>homebrew<<RESET>> directories are in your PATH.
3. Tap the <<BOLD>>homebrew/cask<<RESET>> repository to be able to install casks.
"""

[enabled]
macos = true
manjaro = false

[variables]
POST_CONFIG = [
  "eval (/opt/homebrew/bin/brew shellenv)",
]

[[shell_script_hook]]
name = "INSTALL"
path_to_script = "./bin/hook__install.sh"
priority = 0

[[shell_script_hook]]
name = "INSTALL_PACKAGES"
path_to_script = "./bin/hook__install_packages.sh"
priority = 0

[[variable_status_hook]]
variable_name = "FORMULAE"
path_to_script = "./bin/hook__variable_status.sh"
prepare_step_necessary = true

[[variable_status_hook]]
variable_name = "CASKS"
path_to_script = "./bin/hook__variable_status.sh"
prepare_step_necessary = true
