name = "Docker"
version = "v1.0.0"

documentation = """
Basic docker configuration.
"""

[enabled]
macos = true
manjaro = true

[variables__macos]
CASKS = [
  "docker",
]

[variables__manjaro]
PACMAN = [
  "docker",
]
