name = "Ledger"
version = "v1.0.0"

documentation = """
Ledger accounting package configuration.
"""

[enabled]
macos = true
manjaro = true

[variables__macos]
FORMULAE = [
  "ledger",
]

[variables__manjaro]
PACMAN = [
  "ledger",
]

[[link]]
name = "Configuration file"
path_to_target = "./config/ledgerrc"
path_to_symlink = "$HOME/.config/ledger/ledgerrc"

[[link]]
name = "Accounts script"
path_to_target = "./bin/accounts.bash"
path_to_symlink = "$HOME/.local/bin/my-ledger-accounts"

[[link]]
name = "Base script"
path_to_target = "./bin/base.bash"
path_to_symlink = "$HOME/.local/bin/my-ledger-base"

[[link]]
name = "Daily summary script"
path_to_target = "./bin/daily-summary.bash"
path_to_symlink = "$HOME/.local/bin/my-ledger-daily-summary"

[[link]]
name = "Weekly summary script"
path_to_target = "./bin/weekly-summary.bash"
path_to_symlink = "$HOME/.local/bin/my-ledger-weekly-summary"

[[link]]
name = "Formatter script"
path_to_target = "./bin/formatter.py"
path_to_symlink = "$HOME/.local/bin/my-ledger-formatter"
