name = "Tmux"
version = "v1.0.0"

documentation = """
Advanced tmux configuration.
"""

[enabled]
macos = true
manjaro = true

[variables__macos]
FORMULAE = [
  "tmux",
]

[variables__manjaro]
PACMAN = [
  "tmux",
]

[[links]]
name = "Config file"
path_to_target = "./config/tmux.conf"
path_to_symlink = "$HOME/.config/tmux/tmux.conf"

[[shell_script_hooks]]
name = "INSTALL"
path_to_script = "./bin/hook__install.sh"
priority = 1
