name = "RipGrep"
version = "v1.0.0"

documentation = """
Custom rg configuration.
"""

[enabled]
macos = true
manjaro = true

[variables]
ENV = [
  "RIPGREP_CONFIG_PATH='$HOME/.config/ripgrep/ripgreprc'",
]

[variables__macos]
FORMULAE = [
  "ripgrep",
]

[variables__manjaro]
PACMAN = [
  "ripgrep",
]

[[links]]
name = "Config file"
path_to_target = "./config/ripgreprc"
path_to_symlink = "$HOME/.config/ripgrep/ripgreprc"
