name = "TMUX"
version = "v1.0.0"
enabled = true

documentation = """
Advanced tmux configuration.
"""

[variables]
PACMAN = [
  "tmux",
]

[[links]]
name = "Config file"
path_to_target = "./config/tmux.conf"
path_to_symlink = "$HOME/.config/tmux/tmux.conf"

[[hooks]]
name = "INSTALL"
path_to_script = "./bin/hook__install.sh"
priority = 0
