name = "Tree"
version = "v1.0.0"

documentation = """
Basic config for tree
"""

[enabled]
macos = true
manjaro = true

[variables__macos]
FORMULAE = [
  "tree",
]

[variables__manjaro]
PACMAN = [
  "tree",
]
