name = "Bat"
version = "v1.0.0"
enabled = true

documentation = """
Cat replacement with coloring.

It is mainly used to color man pages without littering the environment with
LESS related coloring variables. With defining the MANPAGER env variable the
man pages are colored in a much cleaner way.
"""

[variables]
PACMAN = [
  "bat",
]
ENV = [
  'MANPAGER=sh -c "col -bx | bat -l man -p"'
]
