name = "Fish"
version = "v1.0.0"
enabled = false

documentation = """
Configuration for the fish shell.
"""

[variables]
PACMAN = [
  "fish",
]
PATH = [
  "$HOME/.local/bin",
]
ALIAS = [
  "dot='cd ~/.dotmodules'",
]

[[links]]
name = "Main fish config file"
path_to_target = "./config/config.fish"
path_to_symlink = "$HOME/.config/fish/config.fish"

[[links]]
name = "Generated script files"
path_to_target = "./config/generated"
path_to_symlink = "$HOME/.config/fish/generated"

[[links]]
name = "Completions config directory"
path_to_target = "./config/completions"
path_to_symlink = "$HOME/.config/fish/completions"

[[links]]
name = "Conf.d config directory"
path_to_target = "./config/conf.d"
path_to_symlink = "$HOME/.config/fish/conf.d"

[[links]]
name = "Functions config directory"
path_to_target = "./config/functions"
path_to_symlink = "$HOME/.config/fish/functions"


[[hooks]]
name = "GENERATE_ALIAS_SCRIPT"
path_to_script = "./bin/hook__generate_alias_script.sh"
priority = 0

[[hooks]]
name = "GENERATE_ENV_SCRIPT"
path_to_script = "./bin/hook__generate_env_script.sh"
priority = 0

[[hooks]]
name = "GENERATE_PATH_SCRIPT"
path_to_script = "./bin/hook__generate_path_script.sh"
priority = 0

[[hooks]]
name = "GENERATE_POST_CONFIG_SCRIPT"
path_to_script = "./bin/hook__generate_post_config_script.sh"
priority = 0
