name = "Fish"
version = "v1.0.0"

documentation = """
Configuration for the fish shell.

After this module gets installed, you need to do the followings to set it up as the main shell:

1. sudo -c 'echo $(which fish) >> /etc/shells'
2. chsh -s $(which fish)
"""

[enabled]
macos = true
manjaro = true

[variables]
PATH = [
  "$HOME/.local/bin",
]
ALIAS = [
  "dot='cd ~/.dotmodules'",
]

[variables__macos]
FORMULAE = [
  "fish",
  "coreutils",
]

[variables__manjaro]
PACMAN = [
  "fish",
]

[[link]]
name = "Main fish config file"
path_to_target = "./config/config.fish"
path_to_symlink = "$HOME/.config/fish/config.fish"

[[link]]
name = "Generated script files"
path_to_target = "./config/generated"
path_to_symlink = "$HOME/.config/fish/generated"

[[link]]
name = "Completions directory"
path_to_target = "./config/completions"
path_to_symlink = "$HOME/.config/fish/completions"

[[link]]
name = "Conf.d config directory"
path_to_target = "./config/conf.d"
path_to_symlink = "$HOME/.config/fish/conf.d"

[[link]]
name = "Functions directory"
path_to_target = "./config/functions"
path_to_symlink = "$HOME/.config/fish/functions"

[[shell_script_hook]]
name = "GENERATE_ALIAS_SCRIPT"
path_to_script = "./bin/hook__generate_alias_script.sh"
priority = 0

[[shell_script_hook]]
name = "GENERATE_ENV_SCRIPT"
path_to_script = "./bin/hook__generate_env_script.sh"
priority = 0

[[shell_script_hook]]
name = "GENERATE_PATH_SCRIPT"
path_to_script = "./bin/hook__generate_path_script.sh"
priority = 0

[[shell_script_hook]]
name = "GENERATE_POST_CONFIG_SCRIPT"
path_to_script = "./bin/hook__generate_post_config_script.sh"
priority = 0

[[shell_script_hook]]
name = "GENERATE_PYTHON_PEP582_SHIM"
path_to_script = "./bin/hook__generate_python_pdm_pep582_shim.sh"
priority = 0

[[variable_status_hook]]
variable_name = "ALIAS"
path_to_script = "./bin/hook__variable_status.sh"
prepare_step_necessary = false

[[variable_status_hook]]
variable_name = "ENV"
path_to_script = "./bin/hook__variable_status.sh"
prepare_step_necessary = false

[[variable_status_hook]]
variable_name = "PATH"
path_to_script = "./bin/hook__variable_status.sh"
prepare_step_necessary = false

[[variable_status_hook]]
variable_name = "POST_CONFIG"
path_to_script = "./bin/hook__variable_status.sh"
prepare_step_necessary = false
