name = "VSCode"
version = "v1.0.0"
enabled = true

documentation = """
Custom configuration for VSCode focusing on vim compatibility.
"""

[variables]
AUR = [
  "visual-studio-code-bin"
]

[[links]]
name = "Setitngs file"
path_to_target = "./config/settings.json"
path_to_symlink = "$HOME/.config/Code/User/settings.json"

[[links]]
name = "Keybindings file"
path_to_target = "./config/keybindings.json"
path_to_symlink = "$HOME/.config/Code/User/keybindings.json"

[[links]]
name = "Spelling dictionary file"
path_to_target = "./config/spellright.dict"
path_to_symlink = "$HOME/.config/Code/User/spellright.dict"
